# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    env:
      OPENSKY_API_URL: https://opensky-network.org/api
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Get BW Secrets
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{secrets.BW_ACCESS_TOKEN}}
          base_url: https://vault.bitwarden.com
          secrets: |
            2e27e175-f9e8-4f99-8e92-b2400033f947 > OPENSKY_API_PASSWORD
            f2aedeb2-e239-456b-bc3b-b2400033c61d > OPENSKY_API_USERNAME
      - run: npm ci
      - run: npm test
